services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: schoolmind_db
      POSTGRES_USER: schoolmind_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn schoolmind.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Параметры подключения к БД внутри контейнера
      - DATABASE_URL=postgres://schoolmind_user:12345@db:5432/schoolmind_db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # Настроен собственный nginx.conf в корне проекта
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Статика хранится в папке public/
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - web

volumes:
  pgdata:
